import Head from 'next/head';
import { Inter } from 'next/font/google';
import HeroSection from '@/components/HeroSection';
import NavBar from '@/components/NavBar';
import AboutMeSection from '@/components/AboutMeSection';
import PortfolioSection from '@/components/PortfolioSection';
import ContactSection from '@/components/ContactSection';
import Footer from '@/components/Footer';
import BackToTopButton from '@/components/utilities/BackToTopButton';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Thomas Albuquerque Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(`https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Share:ital,wght@0,400;0,700;1,400&display=swap`);
        </style>
      </Head>
      <main className="bg-gradient-to-br from-darkBlue to-veryDarkBlue">
        <NavBar />
        <HeroSection />
        <AboutMeSection />
        <PortfolioSection />
        <ContactSection />
        <Footer />
        <BackToTopButton />
      </main>
    </>
  );
}
