import Head from 'next/head';
import HeroSection from '@/components/HeroSection';
import NavBar from '@/components/NavBar';
import AboutMeSection from '@/components/AboutMeSection';
import PortfolioSection from '@/components/PortfolioSection';
import ContactSection from '@/components/ContactSection';
import Footer from '@/components/Footer';
import BackToTopButton from '@/components/utilities/BackToTopButton';
import { Share_Tech_Mono, Share } from 'next/font/google';

const share = Share({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-share',
  display: 'swap',
});
const share_tech_mono = Share_Tech_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-share-tech-mono',
  display: 'swap',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Thomas Albuquerque Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`bg-aBitMoreDarkBlue ${share.variable} ${share_tech_mono.variable}`}>
        <NavBar />
        <HeroSection />
        <AboutMeSection />
        <PortfolioSection />
        <ContactSection />
        <Footer />
        <BackToTopButton />
      </main>
    </>
  );
}
